<?php

namespace AppBundle\Repository;

/**
 * AssetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetRepository extends \Doctrine\ORM\EntityRepository
{
  public function search($minTurnover, $maxTurnover, $minStaff, $maxStaff)
  {
    $searchArgs = '';

    if (!empty($minTurnover)) {
      $searchArgs .= ' AND a.turnover >= ' . ((int)$minTurnover);
    }
    if (!empty($maxTurnover)) {
      $searchArgs .= ' AND a.turnover <= ' . ((int)$maxTurnover);
    }
    if (!empty($minStaff)) {
      $searchArgs .= ' AND a.staff >= ' . ((int)$minStaff);
    }
    if (!empty($maxStaff)) {
      $searchArgs .= ' AND a.staff <= ' . ((int)$maxStaff);
    }

    if (empty($searchArgs)) {
      return $this->findAll();
    }

    return $this->_em->createQuery('SELECT a FROM AppBundle\Entity\Asset a WHERE 1=1' . $searchArgs)
      ->getResult();
  }
}
